.TH flatcam 1 "June 22, 2017" "FlatCAM"

.SH NAME
flatcam \- 2D Computer-Aided PCB Manufacturing on a CNC router.

.SH DESCRIPTION
.PP
FlatCAM is a program for preparing CNC jobs to create prototyps of PCBs on a
CNC router. You can open Gerber, Excellon or G-Code, edit it or create files
from scratch, and output G-Code. Isolation routing is one of many tasks that
FlatCAM is perfect for.  FlatCAM comes with a Tcl Shell interface to automate
steps.

.SH SYNOPSIS
.B flatcam

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
